repos:
  - hooks:
      - id: commitizen
        stages:
          - commit-msg
    repo: https://github.com/commitizen-tools/commitizen
    rev: v2.20.4
  - hooks:
      - id: prettier
    repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.5.1"
