name: Build test - Website

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repo
        uses: actions/checkout@v2
        if: success()
      # Node is required for npm
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
        if: success()
      # Install and build Docusaurus website
      - name: Build Docusaurus website
        run: |
          npm install 
          npm run build
        if: success()
      - name: Finally!
        run: echo "Successful test ✨"
