name: Prettier everywhere

on:
  schedule:
    - cron: 30 05 15 * *
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
          # This is important to fetch the changes to the previous commit
          fetch-depth: 0
          repo-token: ${{ secrets.PAT_GITHUB_TOKEN }}
        if: success()
      - name: Git Pull everything
        run: |
          git fetch
          git pull
        if: success()
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
        if: success()
      - name: Code Formatting (website)
        run: |
          npm i -g prettier
          npx prettier --write . 
      - name: Inspect for Prettier
        run: |
          npm install
          npx prettier --check --ignore src/css/*
        if: success()
      - name: Add Git User
        env: 
          MAILID: ${{secrets.GIT_AUTHOR_EMAIL}}
        run: |
          git config --global user.name "im-coder-lg (Action Triggered)"
          git config --global user.email "${MAILID}"
          
      - name: Push changes
        if: success()
        run: |
          git add .
          git commit -m "style: Code Formatting Workflow" -m "Either triggered by cron or workflow_dispatch" -d "Committed using im-coder-lg's account"
          git push --force
      - name: Final thing
        run: |
          echo "Prettified code ✨"
          curl \
            -H "Title: Prettie workflow success"
            -H "Priority: urgent" \
            -d "Prettier workflow job completed successfully for im-coder-lg/docusaurus-blog ✨" \
            ${NTFY-URI}
        
        env:
          NTFY-URI: ${{secrets.NTFY_URI}}
